# Terraform CI/CD workflow for infrastructure management
name: 'Terraform CI/CD'

# Define workflow triggers
on:
  push: # Trigger on push events
    branches: # Only for these branches
      - develop
      - staging
      - production
      - main
    paths: # Only when changes occur in infrastructure directory
      - 'infrastructure/**'
  pull_request: # Trigger on pull request events
    branches: # For PRs targeting these branches
      - develop
      - staging
      - production
      - main
    paths:
      - 'infrastructure/**'

# Define workflow jobs
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-southeast-2

    defaults:
      run:
        working-directory: infrastructure/environments/${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/production' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.6

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Clean .terraform directory
        run: rm -rf .terraform

      - name: Terraform Init
        id: init
        run: terraform init -input=false -reconfigure

      # Remove this step that sets TF_WORKSPACE
      # - name: Set Terraform Workspace
      #   run: echo "TF_WORKSPACE=dev" >> $GITHUB_ENV

      # Add this step to set WORKSPACE_NAME
      - name: Set Workspace Name
        run: |
          echo "WORKSPACE_NAME=${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/production' && 'prod' || github.ref == 'refs/heads/staging' && 'staging' || 'dev' }}" >> $GITHUB_ENV

      - name: Ensure Terraform Workspace Exists
        run: |
          terraform workspace list | grep -q "^${WORKSPACE_NAME}$" || terraform workspace new ${WORKSPACE_NAME}
          terraform workspace select ${WORKSPACE_NAME}

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      # Step 7: Add comments to pull request
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            # Generate comment content with execution results
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            *Pushed by: @${{ github.actor }}, Environment: \`${process.env.TF_WORKSPACE}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # Step 8: Apply Terraform changes based on branch
      - name: Terraform Apply
        if: github.event_name == 'push' # Only execute on push events
        run: |
          # Apply changes based on the target branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Applying changes to MAIN (PRODUCTION)"
            terraform apply -auto-approve
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            echo "Applying changes to PRODUCTION environment"
            terraform apply -auto-approve
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "Applying changes to STAGING environment"
            terraform apply -auto-approve
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "Applying changes to DEV environment"
            terraform apply -auto-approve
          fi
